version: 0.0
os: linux
files:
  - source: /target/javawebdemo.war
    destination: /tmp/codedeploy-deployment-staging-area/
  - source: /scripts/configure_http_port.xsl
    destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      runas: ec2-user
      timeout: 300
  ApplicationStart:
    - location: scripts/write_codedeploy_config.sh
      runas: ec2-user
    - location: scripts/start_application
      runas: ec2-user
      timeout: 300
  ValidateService:
    - location: scripts/basic_health_check.sh
      runas: ec2-user
